version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting building App - $(date)"
  build:
    commands:
      - echo "Current folder $(pwd)"

      - ls
      - echo $JAVA_HOME
      - echo $GRAALVM_HOME

      - java --version
      - mvn --version
      - aws --version

      - mvn clean install -Pnative
      -
      - echo $JAVA_HOME
      - echo $GRAALVM_HOME

      - java --version
      - mvn --version
      - aws --version

      - ls target
      -
      - aws s3 cp target/function.zip s3://quarkus-poc-artifact/native/function.zip
  post_build:
    commands:
      - echo "Deployment DONE - $(date)"

artifacts:
  files:
    - 'target/function.zip'
  name: afunction.zip